import CONTROLLER_NAME1 from './controllers/CONTROLLER_NAME1';
import CONTROLLER_NAME2 from './controllers/CONTROLLER_NAME2';
import CONTROLLER_NAME3 from './controllers/CONTROLLER_NAME3';
import Authenticate from './models/Authenticate';
import Search from './models/Search';
import MODEL_NAME3 from './models/MODEL_NAME3';
import * as authenticateView from './views/authenticateView';
import * as searchView from './views/searchView';
import * as gameListView from './views/gameListView';
export const controllers = { CONTROLLER_NAME1, CONTROLLER_NAME2, CONTROLLER_NAME3 };
export const models = { Authenticate, Search, MODEL_NAME3 };
export const views = { authenticateView, searchView, gameListView };
export { elements } from './views/base';